config/routes.rb
Rails.application.routes.draw do
  root 'splash_screen#index'
  devise_for :users

  resources :groups do
    resources :entities
  end

  resources :entities, only: %i[index new create destroy]
  resources :groups, only: %i[index new create destroy]

  get 'confirm_email/:token', to: 'users#confirm_email', as: 'confirm_email'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:

    return unless user.role == 'admin'

    can %i[create read update destroy], Group if user.role == 'admin'
    can %i[create read update destroy], Entity if user.role == 'admin'
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :groups

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  include ImageUploader::Attachment(:icon)

  belongs_to :user, class_name: 'User'
  has_many :entities, dependent: :destroy

  validates :name, presence: true

  def total_price
    Entity.where(group_id: id).pluck(:amount).sum
  end
end

app/models/user.rb
class User < ApplicationRecord
  after_create :set_default_role
  after_create :send_confirmation_email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :entities
  has_many :groups

  validates :name, presence: true

  ROLES = %w[admin default].freeze

  def send_confirmation_email
    UserMailer.confirmation_email(self).deliver_now
  end

  private

  def set_default_role
    self.role = 'admin'
    save
  end
end

app/controllers/application_controller.rb
# ApplicationController is the base class for all controllers in your application.
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #   before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[name email password password_confirmation current_password])
  end

  def after_sign_out_path_for(_resource_or_scope)
    root_path
  end

  def after_sign_in_path_for(_resource)
    groups_path # your path
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @entities = @group.entities.order(created_at: :desc)
    @total_price = total_price(@group)
  end

  def total_price(group)
    group.entities.sum(:amount)
  end

  def new
    @entity = Entity.new(name: '')
    @group = Group.find(params[:group_id])
  end

  def create
    @group = Group.find(params[:group_id])
    @entity = @group.entities.build(entity_params)
    @entity.user = current_user

    if @entity.save
      redirect_to group_entities_path(@group), notice: 'Transaction was successfully created.'
    else
      render :new
    end
  end

  def show; end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    # @group.icon_data = params[:group][:icon_data]

    if @group.save
      redirect_to groups_path, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  def show; end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_screen_controller.rb
class SplashScreenController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/splash_screen_helper.rb
module SplashScreenHelper
end

app/views/entities/index.html.erb
<div class="flex flex-col justify-center items-center w-full bg-[#3678C2] h-full">
  <div class="flex flex-col justify-center items-center">
  <h1 class="font-bold text-4xl mt-4 text-white">Transaction</h1>
 
<p class="text-white">Total Amount: $<%= @total_price %></p>
 <div class="p-3"><%= link_to "Back", groups_path %></div>
  </div>
  <div class="w-full flex flex-col justify-center items-center bg-slate-100 p-2 ">
  <div class="flex justify-between items-center w-full">
  <p>Transaction type</p>
  <p>Amount</p>
  <p>Username</p>
  </div>
  <ul class="w-full flex flex-col justify-center items-center">
  <% @entities.each do |entity| %>
  <li class="bg-white p-2 shadow shadow-black w-[90%] flex justify-between items-center">
  <p><%= entity.name %></p>
  <p>$<%= entity.amount %></p>
  <p><%= entity.user.name %></p>
  </li>
  <%end%>
  </ul>
  <div class="mt-4 bg-[#5fb523] w-full flex justify-center items-center p-2">
  <%= link_to 'Add a New Transaction', new_group_entity_path, class: 'bg-[#5fb523] p-2 w-[80%] border border-white text-white text-center' %>
  </div>
  </div>
   
</div>

app/views/entities/new.html.erb
 <div class="p-6 w-full flex-col items-center bg-[#3678C2]">
  <%= notice %>
    <div class='text-center p-2'>
    <h2 class='m-auto font-bold text-white text-3xl'>Add a Transaction</h2>
    <%= link_to 'Back', group_entities_path(@group) %>
    </div>

    <%= form_with model: @entity, url: group_entities_path, method: :post, class: 'flex justify-center items-center flex-col mt-8', local: true do |f| %>
      <div>
        <%= f.text_field :name, placeholder: "Enter Name", class: 'mb-4' %>
      </div>
      <div>
        <%= f.number_field :amount, placeholder: "Enter Amount" %>
      </div>
      <div class='flex'>
      <div class='m-auto bg-blue-300 p-3 rounded-md text-white mt-4'>
        <%= f.submit "Save", class: 'cursor-pointer' %>
      </div>
      </div>
    <% end %>
  </div>

app/views/entities/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Entities#show</h1>
  <p>Find me in app/views/entities/show.html.erb</p>
</div>

app/views/groups/index.html.erb
<div class="flex flex-col justify-center items-center w-full bg-[#3678C2] h-full">
  <h1 class="font-bold text-4xl text-white mt-4">Categories</h1>
  <p class="p-3"><%= button_to "Log Out", destroy_user_session_path, method: :delete %></p>
  <ul class="w-full bg-slate-300 p-2 mt-6">
  <% @groups.each do |group| %>
  <li class="bg-white mb-4 shadow-sm 
  rounded shadow-black p-2">
 <%= link_to group_entities_path(group) do %>
  <div class="flex items-center justify-between">
    <div class="w-16 h-16"><%= image_tag group.icon_url if group.icon %></div>
    <div>
      <p>Category: <%= group.name %></p>
      <p>Name: <%= group.user.name %></p>
      <p>Amount: $<%= group.total_price %></p>
    </div>
  </div>
<% end %>

  </li>
  <%end%>
  </ul>
  <div class=" bg-[#5fb523] w-full flex justify-center items-center p-2">
  <%= link_to 'Add a New Category', new_group_path, class: 'bg-[#5fb523] p-2 w-[80%] border border-white text-white text-center' %>
  </div>
</div>

app/views/groups/new.html.erb
 <div class="p-6 w-full flex-col items-center bg-[#3678C2]">
  <%= notice %>
    <div class='text-center p-2'>
    <h2 class='m-auto font-bold text-white text-3xl'>Add a Category</h2>
    </div>
     <div class="p-3"><%= link_to "Back", groups_path %></div>
    <%= form_with model: @group, url: groups_path, method: :post, class: 'flex justify-center items-center flex-col mt-8', local: true do |f| %>
      <div>
        <%= f.text_field :name, placeholder: "Enter Name", class: 'mb-4' %>
      </div>
    
      <div class="mt-4">
  <%= f.label :icon, class: "block font-medium text-sm text-gray-700" do %>
    Add your icon
  <% end %>
  <%= f.file_field :icon, class: "mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
</div>

      <div class='flex'>
      <div class='m-auto bg-blue-300 p-3 rounded-md text-white mt-4'>
        <%= f.submit "Save", class: 'cursor-pointer' %>
      </div>
      </div>
    <% end %>
  </div>

app/views/groups/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Group#show</h1>
  <p>Find me in app/views/group/show.html.erb</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto px-5 flex flex-col">
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/splash_screen/index.html.erb
<div class="flex flex-col justify-center items-center w-full">
  <h1 class="font-bold text-4xl text-green-400 mb-24 mt-28">Spyrex Fintech</h1>
    <div class="p-3 flex flex-col w-full justify-center items-center"><%= link_to "Log in", new_user_session_path, class: "p-2 w-5/6 text-white bg-green-500 flex justify-center items-center" %>
    <%= link_to "Sign up", new_user_registration_path, class: "mt-4 border-b border-black w-1/6 flex justify-center items-center" %>
    </div>
</div>